version: '3'
services:
  cgm-remote-monitor:
    image: "pyrmon/nightscout:14.2.5-amd"
    environment:
      ## settings according to
      ## https://github.com/nightscout/cgm-remote-monitor/blob/master/README.md#environment

      # MongoDB connection within the stack
      - MONGO_CONNECTION=mongodb://mongo:27017/Nightscout
      # admin secret
      - API_SECRET=xxxxxxxxxxxx
      # the URL to this Nightscout instance
      - BASE_URL=https://ns.xxxxx.com
      # using a reverse proxy with SSL offloading
      - INSECURE_USE_HTTP=true
      # deny access by default
      - AUTH_DEFAULT_ROLES=denied

      # device info fields to show
      - PUMP_FIELDS=reservoir battery status
      # required for other plugins (i.e. upbat)
      - DEVICESTATUS_ADVANCED=true
      # enable plugins
      - ENABLE=careportal delta direction upbat timeago pump bwg rawbg devicestatus openaps
      # tune BG target and alarm ranges (since nightscout 13.0.0 in *display* units)
      - BG_HIGH=190
      - BG_TARGET_TOP=120
      - BG_TARGET_BOTTOM=80
      - BG_LOW=60

      # website title by default
      - CUSTOM_TITLE=Nightscout TL
      # use SI units by default
      - DISPLAY_UNITS=mg/dl
      # use 24h time format by default
      - TIME_FORMAT=24
      # switch to "colors" theme by default
      - THEME=colors
      # switch to German by default
      - LANGUAGE=de
      # show basal rate by default
      - BASAL_RENDER=default
      # show plugins by default
      - SHOW_PLUGINS=pump openaps
      # do not allow treatment editing
      - EDIT_MODE=off
      # disable any alarms by default (if using Nightscout as time series visualization)
      - ALARM_URGENT_HIGH=off
      - ALARM_HIGH=off
      - ALARM_URGENT_LOW=off
      - ALARM_LOW=off
      - ALARM_TIMEAGO_WARN=off
      - ALARM_TIMEAGO_URGENT=off
    ports:
      - 1337:1337
    depends_on:
      - mongo 

  mongo:
    image: mongo:latest
    volumes:
      - ./mongodb:/data/db
    ports:
      - 27017:27017
